# Generated by Django 6.0.3 on 2026-03-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('furniture', 'furniture & furnishing'), ('kitchen', 'Kichen Essentials'), ('Decor', 'Home Decor & Styling'), ('lighting', 'Lighting Solutions'), ('bathroom', 'Bathroom Acessories'), ('home', 'Home Office & Study'), ('technology', 'Smart Home Technology'), ('floor', 'Flooring & Wall Covering'), ('storage', 'Storage & Orginization'), ('security', 'Saftey and Security'), ('cleaning', 'Cleaning Supplies & Equipment'), ('staircase', 'Stair Case & Hallway')], default='home', help_text='Provide a products category'),
        ),
    ]
