# Generated by Django 4.2.29 on 2026-03-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalib', '0002_alter_category_id_alter_services_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='subtitle',
            field=models.CharField(default='', max_length=50),
        ),
    ]
