# Generated by Django 6.0.3 on 2026-03-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalib', '0004_alter_products_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='info',
            field=models.TextField(default='', max_length=500),
        ),
    ]
