# Generated by Django 6.0.3 on 2026-03-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalib', '0005_alter_services_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
